source 'https://rubygems.org'

gem 'i18n', '~> 0.6.9'
gem 'rails', '3.2.16'
gem 'russian'
gem 'jquery-rails'
gem 'pg'
gem 'will_paginate', '~> 3.0.pre2'
gem 'ckeditor'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'unicorn'
gem 'newrelic_rpm'
